name = "mori-space"
main = "./.output/server/index.mjs"
workers_dev = true
compatibility_date = "2024-11-27"
compatibility_flags = [ "nodejs_compat" ]
assets = { directory = "./.output/public/", binding = "ASSETS" }

[vars]
NUXT_PUBLIC_GOOGLE_ANALYTICS_ID = "G-X036TNBC2Q"
NUXT_GOOGLE_ADSENSE_ID = "ca-pub-2810659463174293"